### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by djami97** [TUNNELING-GROUP/aqua-duct#3]
Hi, I'm having problems running the AQUA-DUCT. When I run it putting a gro file in topology and xtc file in the trajectory, it continuosly gives me:

Creating raw paths (sandwich deconvolution):
  0% [                        ] ETA: ?multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/djuraami/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/djuraami/miniconda3/lib/python3.9/site-packages/aquaduct/apps/valve/worker.py", line 75, in __call__
    new_p = GenericPaths((0, self.all_res_ids[pnr]),
  File "/home/djuraami/miniconda3/lib/python3.9/site-packages/aquaduct/traj/paths.py", line 87, in __init__
    assert len(self.name) == 3
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/djuraami/miniconda3/bin/valve.py", line 238, in <module>
    result2 = valve_exec_stage(1, config, stage_II_run, force_save=force_save,
  File "/home/djuraami/miniconda3/lib/python3.9/site-packages/aquaduct/apps/valve/core.py", line 91, in valve_exec_stage
    result = stage_run(config, options, **kwargs)
  File "/home/djuraami/miniconda3/lib/python3.9/site-packages/aquaduct/apps/valve/core.py", line 440, in stage_II_run
    list(map(new_paths.callback_append_next, pool.imap_unordered(pool_func, list(range(len(all_res_ids))))))
  File "/home/djuraami/miniconda3/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
AssertionError

I tried also creating psf file and then saving the xtc to dcd, but I keep getting the same problem.

**Comment by TianmingQu** [comment]
Did you solve the problem?

I also got the same error with my psf file
